Implemented OneWeekView and TwoWeeksView
lilcodelab/Xamarin.Plugin.Calendar pull request #106
Opened 2021-08-06 13:56 UTC by tborozan

New concept **LayoutUnit**:
Represents a week, two weeks or month depending on `CalendarLayout` property

Added:
- CalendarPlugin
    - `CalendarLayout` - indicates selected layout
    - `WeekViewUnit` - represents **LayoutUnit** naming scheme (month name/week number)
    - `ViewLayoutEngine` - generated layout based on `CalendarLayout`
- SampleApp
    - `OneWeekView`
    - `TwoWeeksView`

Renamed:
- `MonthYear` -> `ShownDate`
- `ShowMonthPicker` -> `ShowLayoutUnitPicker`
- `MonthText` -> `LayoutUnitText`
- `PrevMonthCommand` -> `PrevLayoutUnitCommand`
- `NextMonthCommand` -> `PrevLayoutUnitCommand`

2021-09-15 13:50 UTC, m-luketin commented on src/Calendar.Plugin.Sample/SampleApp/ViewModels/AdvancedPageViewModel.cs
> +                   todayEvents.Insert(0, new AdvancedEventModel { Name = "Cool event insert", Description = "This is Cool event's description!", Starting = new DateTime() });
Might be good to name these consistently with the other events. We currently have Cool eventX, Cool event insert and Cool event add, its starting to look a bit messy

2021-09-15 13:51 UTC, m-luketin reviewed
When entering the single and two week view calendar sample, there is a snappy change a few seconds after the page seems fully loaded, and then another one after a second or so. It's confusing for the user opening the sample, especially if they attempt to tap anything.

Its unclear why some events have a margin, while others dont.

2021-09-15 13:56 UTC, m-luketin commented on src/Calendar.Plugin.Sample/SampleApp/ViewModels/AdvancedPageViewModel.cs
> +            switch (CalendarLayout)
I think most of this is excess logic. Could we not just have a ChangeShown method (the same as ChangeShownWeek, where we send the proper parameter for changing the month aswell?

2021-09-15 14:07 UTC, m-luketin commented on src/Calendar.Plugin/Shared/Controls/ViewLayoutEngines/MonthViewEngine.cs
> +                6
Separate magic number into a named private variable

2021-09-17 13:53 UTC, dujesaric commented on src/Calendar.Plugin/Shared/Controls/ViewLayoutEngines/ViewLayoutBase.cs
> +                for (int ii = 0; ii < 7; ii++)
Could we separate looping integers with constants? NumberOfDaysInWeek?

2021-09-23 11:23 UTC, m-luketin approved these changes
Everything seems in order. I just want to mention that, until now, days that don't belong to the selected month had the disabled color, which is not the case on the 1 and 2 week calendars. If this is intended then ok. (e.g. if we are on september, and the 1st and 2nd of october are visible, they would have the disabled color for the date number)

2021-10-03 16:52 UTC, antonioseric requested changes
something is wrong with event list when there is 5 or less events
![Screenshot_1633279628](https://user-images.githubusercontent.com/4761328/135763697-9a099ad1-c45e-4a63-aed6-80dd889adddd.png)

2021-10-11 09:18 UTC, merged

2022-03-18 09:56 UTC, inimirpaz commented
> * `PrevMonthCommand` -> `PrevLayoutUnitCommand`
> 
> * `NextMonthCommand` -> `PrevLayoutUnitCommand`

The second one is actually `NextLayoutUnitCommand`