Range selection
lilcodelab/Xamarin.Plugin.Calendar pull request #80
Opened 2021-03-30 14:42 UTC by m-luketin

Implemented date range selection functionality.

- Added new Advanced Calendar page to SampleApp and moved the range picker from the previous Advanced page
- Implemented selection behaviour modelled after third-party calendars
- Added Clear functionality to pop-ups in SampleApp
- Refactored some contributor code
- Handled a number of single selection bugs that arose in the process

2021-03-31 07:10 UTC, antonioseric requested changes
Also don't forget to add images for Ranged and documentation in Readme.md

2021-03-31 07:10 UTC, antonioseric commented on src/Calendar.Plugin/Shared/Controls/MonthDaysView.xaml.cs
> +                case nameof(RangeSelectionEndDate):                    UpdateDays(AnimateCalendar);
UpdateDays should be in new line

2021-03-31 08:08 UTC, m-luketin commented on src/Calendar.Plugin.Sample/SampleApp/ViewModels/AdvancedPageViewModel.cs
> +        public ICommand OpenRangePickerCommand => new Command(async () =>
Definitely, removed now.

2021-04-01 07:13 UTC, antonioseric requested changes

2021-04-01 07:13 UTC, antonioseric commented on README.md
Documentation for new property is still missing, please add i markdown new section how to use/turn on this feature

2021-04-01 07:13 UTC, antonioseric commented on src/Calendar.Plugin/CalendarPlugin - Backup.csproj
> +﻿<Project Sdk="MSBuild.Sdk.Extras/2.1.2">
this needs to be removed

2021-04-01 07:13 UTC, antonioseric commented on src/Calendar.Plugin/CalendarPlugin - Backup.csproj
> +﻿<Project Sdk="MSBuild.Sdk.Extras/2.1.2">
This should be removed

2021-04-01 07:13 UTC, antonioseric commented on src/Calendar.Plugin/CalendarPlugin.csproj
> +    <TargetFrameworks>netstandard2.0;MonoAndroid10.0;MonoAndroid90;Xamarin.iOS10</TargetFrameworks>
this is still there

2021-04-01 07:13 UTC, antonioseric commented on src/Calendar.Plugin/CalendarPlugin.csproj
> +﻿<Project Sdk="MSBuild.Sdk.Extras/2.1.2">
please change version to `3.0.23`

2021-04-01 07:13 UTC, antonioseric commented on src/Calendar.Plugin/Shared/Enums/SelectionType.cs
> +        /// Day title maximum length of one character.
comments are false

2021-04-01 07:13 UTC, antonioseric commented on README.md
also change Supported versions, forms to 4.5+ and android to 10.0+ and ios 9.0+

2021-04-01 08:50 UTC, bbazina commented on src/Calendar.Plugin.Sample/SampleApp/ViewModels/AdvancedRangeSelectionPageViewModel.cs
> +                Console.WriteLine(message);
this should be removed

2021-04-01 08:50 UTC, bbazina commented on src/Calendar.Plugin.Sample/SampleApp/ViewModels/AdvancedRangeSelectionPageViewModel.cs
> +            Console.WriteLine(message);
this should be removed

2021-04-01 08:50 UTC, bbazina commented on src/Calendar.Plugin.Sample/SampleApp/ViewModels/AdvancedRangeSelectionPageViewModel.cs
> +                Console.WriteLine(message);
this should be removed

2021-04-02 06:58 UTC, antonioseric approved these changes

2021-04-02 07:00 UTC, merged